export { default as Dashboard } from './Dashboard';
export { default as Consultation } from './Consultation';
export { default as HealthTracker } from './HealthTracker';
export { default as HealthAssessment } from './HealthAssessment';
export { default as Profile } from './Profile';
export { default as About } from './About';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as ProfileSetup } from './ProfileSetup';